name: deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    - run: npm install
    - run: npm run stage-prod-keys
      env:
        PROD_API_KEY: ${{ secrets.API_KEY }}
        PROD_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        PROD_DIM_API_KEY: ${{ secrets.DIM_API_KEY }}
    - run: npx ng build --configuration production
    - name: Deploy via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.UID }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH }}
        source: "./dist/"
        target: "/home/${{ secrets.UID }}/d2checklist/"
        strip_components: 2 # this is important
